apiVersion: v1
kind: Pod
metadata:
  name: resource-health-test-client-pod
  namespace: resource-health-sandbox
spec:
  containers:
  - name: curl-client
    image: python:3.11.9-slim-bullseye
    command: ["sh", "-c"]
    args:
    - |
      update-ca-certificates
      apt update
      apt install -y curl
      while true; do curl -s https://resource-health-test-service.resource-health-sandbox.svc.cluster.local 2>&1 ; echo "..."; sleep 5; done
      #while true; do curl --cacert /etc/ssl/certs/eoepca.crt -s https://resource-health-test-service.resource-health-sandbox.svc.cluster.local 2>&1 ; echo "..."; sleep 5; done
    volumeMounts:
      - mountPath: "/usr/local/share/ca-certificates/eoepca.crt"
        name: tls-certs
        subPath: ca.crt
        readOnly: true
  volumes:
    - name: tls-certs
      secret:
        secretName: resource-health-test-certificate
