kind: Service
apiVersion: v1
metadata:
  name: resource-health-test-service
  namespace: resource-health-sandbox
spec:
  selector:
    app: resource-health-test-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
