apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-health.fullname" . }}-check-api
  labels:
    app.kubernetes.io/component: "checkapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.check_api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "checkapi"
      {{- include "resource-health.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: "checkapi"
        {{- include "resource-health.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resource-health.fullname" . }}-check-manager
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.healthchecks.use_template_configmap }}
        - name: check-api-templates
          configMap:
            name: {{ include "resource-health.fullname" . }}-check-templates-configmap
        {{- end }}
        {{- if .Values.check_api.use_hook_configmap }}
        - name: check-api-hooks
          configMap:
            name: {{ include "resource-health.fullname" . }}-api-hooks-configmap
        {{- end }}
        {{- range .Values.check_api.configmapMounts }}
        - name: {{ toYaml .name | trim }}
          configMap:
            name: {{ toYaml .configmapName | trim }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.check_api.image.repository }}:{{ .Values.check_api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.check_api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.check_api.containerPort }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.healthchecks.use_template_configmap }}
            - name: check-api-templates
              mountPath: /app/templates/
            {{- end }}
            {{- if .Values.check_api.use_hook_configmap }}
            - name: check-api-hooks
              mountPath: /app/hooks/
            {{- end }}
            {{- range .Values.check_api.configmapMounts }}
            - name: {{ toYaml .name | trim }}
              mountPath: {{ toYaml .mountPath | trim }}
            {{- end }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.check_api.overrideOTLPEndpoint | default .Values.global.defaultOTLPEndpoint }}
            - name: CHECK_MANAGER_COLLECTOR_TLS_SECRET
              value: {{ include "resource-health.fullname" . }}-healthchecks-certificate
            - name: RH_CHECK_K8S_TEMPLATE_PATH
              value: "/app/templates/"
            - name: RH_CHECK_API_BASE_URL
              value: {{ toYaml .Values.global.defaultCheckAPIBaseURL }}
          {{- range .Values.check_api.environmentSecrets }}
            - name: {{ toYaml .name | trim }}
              valueFrom:
                secretKeyRef:
                  name: {{ toYaml .secret | trim }}
                  key: {{ toYaml .key | trim }}
          {{- end }}
          {{- range .Values.check_api.environmentFixed }}
            - name: {{ toYaml .name | trim }}
              value: {{ toYaml .value | trim }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /docs
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
