apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-health.fullname" . }}-check-api
  labels:
    app.kubernetes.io/component: "checkapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.check_api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "checkapi"
      {{- include "resource-health.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: "checkapi"
        {{- include "resource-health.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resource-health.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.check_api.image.repository }}:{{ .Values.check_api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.check_api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.check_api.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
