apiVersion: v1
kind: Service
metadata:
  name: resource-health-check-api
  labels:
    app.kubernetes.io/component: "checkapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.check_api.serviceType }}
  ports:
    - port: {{ .Values.check_api.servicePort }}
      targetPort: {{ .Values.check_api.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "checkapi"
    {{- include "resource-health.selectorLabels" . | nindent 4 }}
