apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource-health.fullname" . }}-check-manager-role
  labels:
    app.kubernetes.io/component: "checkapi"
    {{- include "resource-health.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"] 
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "watch", "list", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"] # "" indicates the core API group
  verbs: ["get", "watch", "list", "create", "patch", "delete"]
