apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "resource-health.fullname" . }}-check-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "resource-health.fullname" . }}-check-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "resource-health.fullname" . }}-check-manager-role
  apiGroup: rbac.authorization.k8s.io