apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource-health.fullname" . }}-check-manager
  labels:
    {{- include "resource-health.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
