apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource-health.fullname" . }}-role-cronjob-manager
  labels:
    app.kubernetes.io/component: "api"
    {{- include "resource-health.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["cronjobs"]
  verbs: ["get", "watch", "list", "create", "patch", "delete"]
