apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "resource-health.fullname" . }}-default-cronjob-manager
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "resource-health.fullname" . }}-role-cronjob-manager
  apiGroup: rbac.authorization.k8s.io