apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-health.fullname" . }}-mockapi
  labels:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mockapi.serviceType }}
  ports:
    - port: {{ .Values.mockapi.servicePort }}
      targetPort: {{ .Values.mockapi.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health.selectorLabels" . | nindent 4 }}
