apiVersion: v1
kind: Service
metadata:
  name: resource-health-mock-api
  labels:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mock_api.serviceType }}
  ports:
    - port: {{ .Values.mock_api.servicePort }}
      targetPort: {{ .Values.mock_api.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health.selectorLabels" . | nindent 4 }}
