apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-health.fullname" . }}-telemetry-api
  labels:
    app.kubernetes.io/component: "api"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.telemetry_api.serviceType }}
  ports:
    - port: {{ .Values.telemetry_api.servicePort }}
      targetPort: {{ .Values.telemetry_api.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "api"
    {{- include "resource-health.selectorLabels" . | nindent 4 }}
