apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-health.fullname" . }}-telemetry-api
  labels:
    app.kubernetes.io/component: "telemetryaccess"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.telemetry_api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "telemetryaccess"
      {{- include "resource-health.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: "telemetryaccess"
        {{- include "resource-health.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resource-health.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: client-tls
          secret:
            ## TODO: Implement more restricted privileges
            secretName: opensearch-admin-certificate
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.telemetry_api.image.repository }}:{{ .Values.telemetry_api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.telemetry_api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.telemetry_api.containerPort }}
              protocol: TCP
          volumeMounts:
          - name: client-tls
            readOnly: true
            mountPath: "/certs"
          ## TODO: add probe endpoints
          livenessProbe:
            httpGet:
              path: /docs
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
