apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-health.fullname" . }}-testrun-cronjob
  labels:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.test_run.schedule }}"
  jobTemplate:
    spec:
      metadata:
        {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        labels:
          app.kubernetes.io/component: "test_run"
          {{- include "resource-health.selectorLabels" . | nindent 8 }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        serviceAccountName: {{ include "resource-health.serviceAccountName" . }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 8 }}
        containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.test_run.image.repository }}:{{ .Values.test_run.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.test_run.image.pullPolicy }}
            ## TODO: Un-hardcode this
            command: ["bash", "-c"]
            args: ["poetry install; sleep 10; poe test --user-id johny1789; poe test --user-id 123potato123; sleep 10"]
            env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.resource-health-opensearch.svc.cluster.local:4317
            - name: MOCK_API_HOST
              value: http://mock_api:5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}

