apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-health.fullname" . }}-web
  labels:
    app.kubernetes.io/component: "web"
    {{- include "resource-health.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.serviceType }}
  ports:
    - port: {{ .Values.web.servicePort }}
      targetPort: {{ .Values.web.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "web"
    {{- include "resource-health.selectorLabels" . | nindent 4 }}
