apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-certificate
  labels:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health-reference-deployment.labels" . | nindent 4 }}
spec:
  secretName: opensearch-admin-certificate
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: opensearch-admin
  issuerRef:
    {{- toYaml .Values.internalIssuerRef | nindent 4 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
