apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-client-certificate
  labels:
    app.kubernetes.io/component: "mockapi"
    {{- include "resource-health-reference-deployment.labels" . | nindent 4 }}
spec:
  secretName: otel-collector-client-certificate
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: otel-collector
  #dnsNames:
  #  - "resource-health-opensearch-dashboards.resource-health-opensearch.svc.cluster.local"
  #  - "resource-health-opensearch-dashboards"
  issuerRef:
    {{- toYaml .Values.internalIssuerRef | nindent 4 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
