---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sensmetry-user-secret
  namespace: resource-health
spec:
  encryptedData:
    password: AgCuFYaUhnH1blVQx4cR409h0r3OShIFoWa9y1wxMfpcO5qtmlooRlJ7yhij6NPd2ncyYtsAu2yd9376VATbsoKdtnz0maF7NMrBmjZfg5mKWBu3l8/0jheDZRHpPvVo93pMGNfP60grfibrODDt63fk0sA4Av2Ygg6THxbu3o1MLOTCm9IZsfczz6/sqHP1sGoSBVSywOwd1/jh0/EzSAnN601SSoGSeWCS8UY+7cWCu7YDsvIdCeVcW4KTIaHZNCugUJInq5kLXZbURoQ8DCcbAXZynNaRW9gQEjw4f+FTdIoguE3uXNu2yfC+iji+kzPmBy2Z6qfPpGUUSZKREI77DXm3ZDel4A8hQsHlyoRKsCEdeF/7s4DE9vFkkqK9WGxBXzRrlTSiZNL3kjeJZ6HzHAtCvA1zsT11hWDSi2k3xBGiYoJo0Mc02Wjbnwp6SEGjplWfGYgDRiFmrgsrfbHEshnHD821NJH8PQ7hgQ2kG3hRdAhBERA7TCzp6/IxuHO9pnE0HVLklVK05eyvmDkLVLcgAJ7jxDHy25sw5eBXm9c6vwfaE5M0T/awUTEY6K8uqs01CujGZ60LqYLCYYGCqIviFopmrBXe6r8YXHAzOewDwUl9JAXbcLKkaDY4UauMTPs+wPSGqjmqvxxh31itrg0e9DBuk7MetBXVJIYAvrrhs4BXjho/mufv+Ro0dsShD4OpyGzwQ8Sprj5WxIg=
    username: AgBoENEVb9Gr9hOfP1I3yIaHBb8L3LiNxIAKWVyVPh//noorUUoaI0MOtQmnD7nC9ATMp5h6I5KcrG/Y615/B6hPWu8hIiBkxljPogqmeVtJDGkbUtDH17gYsXpKA3ROyqL7Lqzj6dHHvoqhwUyl2vOq92AyoEh77uORDpcU9Ta7WQV0Mr00dH2jUOouzei96+Sh0HEBlVmxfjqZgpDZkSAFy9bwwWssqyeWF0rCb7M5BqGnlyGoMXLiEr8OifygBzWSkfzOpfHkJydodg2bQMrVCyeybejOkion/kxlmKLCP8OnqX083fQ8bhWxGYdPx6ShwxBAU0m3k10yl/EG/8DGlwp0W/Evjf1POJXp9L/m5Qu/XIAmfZ4GzeBJeGGmBxtU0luJaKz+g2A+aVp/vaXu0qvTtBKF5FYLJE5E39mB231rXDQRr+tisbMqD/iUBomNW8kMyRWuFFWVvLA2BvGkSPmaosXB1J2ycreWm7G+OYVSm9k0Hij5Ce6x1xVyOanDQJTCehwRxGh2N+3xpVwGEOU2jP/dd8FTfgDo+LACha3bie2+mA/clcvC43sx7mYpk3W4IRi4v3iPG+aVIy6ndDxPQcp8dkWWmO/MtSjbF4YOwNJyDpmQNbmkcTNQxrTTbBX+u9Fs/K+OWgdY22T6mBrddFUKguhd2e1E2msbOn1363QL8NsBqmnDqX6guCgT3FlaEViYqx3l
  template:
    metadata:
      creationTimestamp: null
      name: sensmetry-user-secret
      namespace: resource-health
    type: Opaque
