[project]
name = "check-alerting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "opentelemetry-betterproto>=2.0.0",
]

[dependency-groups]
dev = [
    # Exact versions used by opentelemetry-betterproto
    "betterproto[compiler]~=2.0.0b7",
    "grpcio-tools~=1.66.2",
    # "grpclib>=0.4.8",
    "grpc-stubs>=1.53.0.6",
    "mypy>=1.18.2",
]

[tool.uv.sources]
opentelemetry-betterproto = { git = "https://github.com/EOEPCA/opentelemetry-betterproto.git", branch = "2.0.0" }

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
show_error_context = true
pretty = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
ignore_missing_imports = true
follow_untyped_imports = true
