apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-health
  namespace: argocd
  labels:
    eoepca/is-root-app: "true"
    eoepca/app-name: resource-health
spec:
  project: eoepca
  source:
    repoURL: 'https://github.com/EOEPCA/resource-health'
    path: helm
    targetRevision: deploy-develop
    helm:
      valueFiles:
        - eoepca-develop-values.yaml
  destination:
    namespace: resource-health
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
