apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-health-core
  namespace: argocd
spec:
  project: eoepca
  source:
    repoURL: 'https://github.com/EOEPCA/resource-health'
    path: helm
    targetRevision: tw/update-deployment
    helm:
      valueFiles:
        - eoepca-develop-values.yaml
  destination:
    namespace: resource-health-core
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
