import type { Metadata } from "next";
import "./globals.css";
// import { Provider } from "@/components/ui/provider"
import { ChakraProvider } from "@chakra-ui/react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html suppressHydrationWarning>
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
        {/* <Provider>{children}</Provider> */}
      </body>
    </html>
  )
}

