# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/trace_info.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime

import betterproto


class TraceInfoStatusCode(betterproto.Enum):
    RECEIVING = 0
    PROCESSING = 1
    PROCESSED = 2


@dataclass(eq=False, repr=False)
class TraceInfo(betterproto.Message):
    last_seen: datetime = betterproto.message_field(1)
    status: "TraceInfoStatusCode" = betterproto.enum_field(2)
